Repository paion-data/athena, pull requests merged in 2024-05, with the labels that each got.

#53 Revert "Remove unused rest-assured dependency (#74)"
  pom.xml
Labels: NEED 1 REVIEW, REFACTORING

#45 Implement integration tests
  athena-spring/athena-spring-boot-autoconfigure/pom.xml
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/config/FileControllerConfig.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/controller/FileController.java
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/config/FileControllerConfigSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/config/MetaControllerConfigSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/controller/FileControllerITSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/java/com/paiondata/athena/spring/boot/autoconfigure/TestApplication.java
  athena-spring/athena-spring-boot-autoconfigure/src/test/java/com/paiondata/athena/spring/boot/autoconfigure/TestOss.java
  athena-spring/athena-spring-boot-autoconfigure/src/test/java/com/paiondata/athena/spring/boot/autoconfigure/config/FileControllerITConfig.java
  athena-spring/athena-spring-boot-autoconfigure/src/test/resources/application-test.yml
  athena-spring/athena-spring-boot-autoconfigure/src/test/resources/pride-and-prejudice-by-jane-austen.txt
  checkstyle.xml
  pom.xml
Labels: BREAKING CHANGE, NEED 1 REVIEW

#52 增加 healthcheck
  athena-spring/athena-spring-boot-autoconfigure/pom.xml
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/AbstractITSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/actuator/HealthCheckITSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/controller/FileControllerITSpec.groovy
Labels: CONFIG, MERGEABLE, NEW FEATURE

#54 编写 Swagger 集成测试
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/HealthCheckITSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/OpenApiITSpec.groovy
Labels: CI/CD, MERGEABLE

#55 绑定文档域名
  .github/workflows/ci-cd.yml
  docs/CNAME
  docs/docusaurus.config.ts
Labels: CI/CD, DOCUMENTATION, MERGEABLE

#60 修复项目中 spring 封装下的接口所存在的问题
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/config/WebConfig.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/controller/FileController.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/controller/MetaController.java
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/controller/FileControllerITSpec.groovy
Labels: BUG, NEED 1 REVIEW

#61 更新文档网站 favicon
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
Labels: DOCUMENTATION, NEED 1 REVIEW
