Repository paion-data/athena, pull requests merged in 2024-04, with the labels that each got.

#7 Publish Athena to Maven Central
  .github/tag-for-release.bash
  .github/upversion.py
  .github/workflows/ci-cd.yml
  README.md
  athena-core/pom.xml
  athena-examples/athena-example-books/Dockerfile
  athena-examples/athena-example-books/pom.xml
  athena-examples/athena-examples-acceptance-tests/README.md
  athena-examples/athena-examples-acceptance-tests/pom.xml
  athena-examples/athena-examples-acceptance-tests/src/test/java/com/paiondata/athena/test/acceptance/AbstractStepDefinitions.java
  athena-examples/athena-examples-acceptance-tests/src/test/java/com/paiondata/athena/test/acceptance/FileStepDefinitions.java
  athena-examples/athena-examples-acceptance-tests/src/test/java/com/paiondata/athena/test/acceptance/InitStepDefinitions.java
  athena-examples/athena-examples-acceptance-tests/src/test/java/com/paiondata/athena/test/acceptance/MetadataStepDefinitions.java
  athena-examples/athena-examples-acceptance-tests/src/test/java/com/paiondata/athena/test/acceptance/RunCucumberTest.java
  athena-examples/athena-examples-acceptance-tests/src/test/resources/com/paiondata/athena/test/acceptance/file.feature
  athena-examples/athena-examples-acceptance-tests/src/test/resources/com/paiondata/athena/test/acceptance/metadata.feature
  athena-examples/athena-examples-acceptance-tests/src/test/resources/file/pride-and-prejudice-by-jane-austen.txt
  athena-examples/athena-examples-acceptance-tests/src/test/resources/path-param/multiple-fields-metadata-request.graphql
  athena-examples/athena-examples-acceptance-tests/src/test/resources/path-param/single-field-metadata-request.graphql
  athena-examples/athena-examples-acceptance-tests/src/test/resources/payload/multiple-fields-metadata-request.json
  athena-examples/athena-examples-acceptance-tests/src/test/resources/payload/multiple-fields-metadata-response.json
  athena-examples/athena-examples-acceptance-tests/src/test/resources/payload/single-field-metadata-request.json
  athena-examples/athena-examples-acceptance-tests/src/test/resources/payload/single-field-metadata-response.json
  athena-examples/athena-examples-acceptance-tests/src/test/resources/payload/uploaded-file-metadata-request.json
  athena-examples/athena-examples-acceptance-tests/src/test/resources/payload/uploaded-file-metadata-response.json
  athena-examples/pom.xml
  athena-filestore/athena-filestore-swift/pom.xml
  athena-filestore/pom.xml
  athena-metastore/athena-metastore-graphql/pom.xml
  athena-metastore/pom.xml
  athena-system-config/pom.xml
  pom.xml
Labels: CI/CD, CONFIG, MERGEABLE

#12 Fix release error
  .github/workflows/ci-cd.yml
  pom.xml
Labels: BUG, CI/CD, NEED 1 REVIEW

#14 Specify GPG keyname during release process
  .github/workflows/ci-cd.yml
Labels: BUG, CI/CD, NEED 1 REVIEW

#16 Local version should be SNAPSHOT
  athena-core/pom.xml
  athena-examples/athena-example-books/Dockerfile
  athena-examples/athena-example-books/pom.xml
  athena-examples/pom.xml
  athena-filestore/athena-filestore-swift/pom.xml
  athena-filestore/pom.xml
  athena-metastore/athena-metastore-graphql/pom.xml
  athena-metastore/pom.xml
  athena-system-config/pom.xml
  pom.xml
Labels: BUG, NEED 1 REVIEW

#17 Fix Docker image release
  .github/workflows/ci-cd.yml
Labels: BUG, CI/CD, NEED 1 REVIEW

#15 移除 .newInstance() 方法
  athena-core/src/main/java/com/paiondata/athena/application/ResourceConfig.java
  athena-examples/athena-example-books/src/main/java/com/paiondata/athena/example/books/application/BooksBinderFactory.java
  athena-system-config/src/main/java/com/paiondata/athena/config/SystemConfigFactory.java
  docs/.gitignore
Labels: BUG, NEED 1 REVIEW

#19 将文档迁移至 Docusaurus
  .github/workflows/ci-cd.yml
Labels: DOCUMENTATION, MERGEABLE

#22 Support AliCloud OSS
  athena-core/src/main/java/com/paiondata/athena/application/AbstractBinderFactory.java
  athena-core/src/main/java/com/paiondata/athena/application/BinderFactory.java
  athena-core/src/main/java/com/paiondata/athena/application/ResourceConfig.java
  athena-core/src/main/java/com/paiondata/athena/file/File.java
  athena-core/src/main/java/com/paiondata/athena/file/identifier/FileIdGenerator.java
  athena-core/src/main/java/com/paiondata/athena/file/identifier/FileNameAndUploadedTimeBasedIdGenerator.java
  athena-core/src/main/java/com/paiondata/athena/filestore/FileStore.java
  athena-core/src/main/java/com/paiondata/athena/metadata/FileType.java
  athena-core/src/main/java/com/paiondata/athena/metadata/MetaData.java
  athena-core/src/main/java/com/paiondata/athena/metastore/MetaStore.java
  athena-core/src/main/java/com/paiondata/athena/web/endpoints/FileServlet.java
  athena-core/src/main/java/com/paiondata/athena/web/endpoints/MetaServlet.java
  athena-core/src/main/java/com/paiondata/athena/web/graphql/JacksonParser.java
  athena-core/src/main/java/com/paiondata/athena/web/graphql/JsonDocumentParser.java
  athena-core/src/test/groovy/com/paiondata/athena/application/AbstractBinderFactorySpec.groovy
  athena-core/src/test/groovy/com/paiondata/athena/application/MockingBinderFactory.groovy
  athena-core/src/test/groovy/com/paiondata/athena/application/ResourceConfigSpec.groovy
  athena-core/src/test/groovy/com/paiondata/athena/file/identifier/FileNameAndUploadedTimeBasedIdGeneratorSpec.groovy
  athena-core/src/test/groovy/com/paiondata/athena/metadata/FileTypeSpec.groovy
  athena-core/src/test/groovy/com/paiondata/athena/metadata/MetaDataSpec.groovy
  athena-core/src/test/groovy/com/paiondata/athena/web/endpoints/FileServletSpec.groovy
  athena-core/src/test/groovy/com/paiondata/athena/web/endpoints/MetaServletSpec.groovy
  athena-core/src/test/groovy/com/paiondata/athena/web/graphql/JacksonParserSpec.groovy
  athena-core/src/test/groovy/com/paiondata/athena/web/graphql/JsonDocumentParserSpec.groovy
  athena-core/src/test/java/com/paiondata/athena/application/ApplicationState.java
  athena-core/src/test/java/com/paiondata/athena/application/JerseyTestBinder.java
  athena-core/src/test/java/com/paiondata/athena/application/TestBinderFactory.java
  athena-core/src/test/java/com/paiondata/athena/application/TestMutationDataFetcher.java
  athena-core/src/test/java/com/paiondata/athena/application/TestQueryDataFetcher.java
  athena-core/src/test/java/com/paiondata/athena/filestore/TestFileStore.java
  athena-core/src/test/java/com/paiondata/athena/metastore/TestMetaStore.java
  athena-examples/athena-example-books/src/main/java/com/paiondata/athena/example/books/application/BooksBinderFactory.java
  athena-examples/athena-example-books/src/main/java/com/paiondata/athena/example/books/application/SQLMutationDataFetcher.java
  athena-examples/athena-example-books/src/main/java/com/paiondata/athena/example/books/application/SQLQueryDataFetcher.java
  athena-examples/athena-example-books/src/test/java/com/paiondata/athena/example/books/application/BookJerseyTestBinder.java
  athena-filestore/athena-filestore-alioss/pom.xml
  athena-filestore/athena-filestore-alioss/src/main/java/com/paiondata/athena/filestore/alioss/AliOSSFileStore.java
  athena-filestore/athena-filestore-alioss/src/test/groovy/com/paiondata/athena/filestore/alioss/AliOSSFileStoreSpec.groovy
  athena-filestore/athena-filestore-swift/src/main/java/com/paiondata/athena/filestore/swift/SwiftFileStore.java
  athena-filestore/pom.xml
  athena-metastore/athena-metastore-graphql/src/main/java/com/paiondata/athena/metastore/graphql/GraphQLFactory.java
  athena-metastore/athena-metastore-graphql/src/main/java/com/paiondata/athena/metastore/graphql/GraphQLMetaStore.java
  athena-metastore/athena-metastore-graphql/src/main/java/com/paiondata/athena/metastore/graphql/query/GraphQLQueryProvider.java
  athena-metastore/athena-metastore-graphql/src/main/java/com/paiondata/athena/metastore/graphql/query/GraphQLQueryProviderFactory.java
  athena-metastore/athena-metastore-graphql/src/main/java/com/paiondata/athena/metastore/graphql/query/TemplateBasedGraphQLQueryProvider.java
  athena-system-config/src/main/java/com/paiondata/athena/config/ConfigResourceLoader.java
  athena-system-config/src/main/java/com/paiondata/athena/config/ErrorMessageFormat.java
  athena-system-config/src/main/java/com/paiondata/athena/config/LayeredFileSystemConfig.java
  athena-system-config/src/main/java/com/paiondata/athena/config/MessageFormatter.java
  athena-system-config/src/main/java/com/paiondata/athena/config/SystemConfig.java
  athena-system-config/src/main/java/com/paiondata/athena/config/SystemConfigFactory.java
  checkstyle.xml
Labels: BREAKING CHANGE, NEED CHANGES

#24 Add maven central badge
  README.md
Labels: DOCUMENTATION, MERGEABLE

#31 使用公司的发布插件将 Athena 发布到 Maven Central
  .github/workflows/ci-cd.yml
Labels: CI/CD, REFACTORING

#33 Fix action name
  .github/workflows/ci-cd.yml
Labels: BUG, CI/CD

#32 Enhance documentation frontpage
  docs/docs/filestores/index.md
  docs/docs/glossary.md
  docs/docusaurus.config.ts
  docs/sidebars.ts
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/css/custom.css
  docs/src/pages/index.tsx
  docs/static/img/big-data.svg
  docs/static/img/graphql.svg
  docs/static/img/object-storage.svg
  docs/static/img/openstack.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
Labels: DOCUMENTATION, MERGEABLE, REFACTORING

#34 Remove unused rest-assured dependency (#74)
  pom.xml
Labels: NEED 1 REVIEW, REFACTORING

#37 支持在 athena-spring-boot-starter 中自动生成 Maven Central 发布需要的 javadoc 和 sources JAR
  pom.xml
Labels: BUG, CI/CD, NEED 1 REVIEW

#40 修复 ResourceConfig 无法在 Docker 容器里被自动扫描的问题
  athena-examples/athena-example-books/Dockerfile
  athena-examples/athena-example-books/Dockerfile-startup.sh
  athena-examples/athena-example-books/pom.xml
  athena-examples/athena-example-books/src/main/resources/applicationConfig.properties
  docs/docs/contributing/development.md
  docs/docs/contributing/img/download-jetty.png
  pom.xml
Labels: BUG, NEED 1 REVIEW

#43 Catch up checkstyle with JDK 17
  athena-core/src/main/java/com/paiondata/athena/file/File.java
  athena-core/src/main/java/com/paiondata/athena/file/identifier/FileNameAndUploadedTimeBasedIdGenerator.java
  athena-core/src/main/java/com/paiondata/athena/metadata/MetaData.java
  athena-core/src/main/java/com/paiondata/athena/web/graphql/JacksonParser.java
  athena-core/src/test/java/com/paiondata/athena/application/JerseyTestBinder.java
  athena-filestore/athena-filestore-alioss/src/main/java/com/paiondata/athena/filestore/alioss/AliOSSFileStore.java
  athena-metastore/athena-metastore-graphql/src/main/java/com/paiondata/athena/metastore/graphql/GraphQLFactory.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/config/BeanConfig.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/controller/FileController.java
  athena-system-config/src/main/java/com/paiondata/athena/config/LayeredFileSystemConfig.java
  checkstyle-suppressions.xml
  checkstyle.xml
  pom.xml
Labels: BUG, MERGEABLE

#39 文件原数据读取
  athena-spring/athena-spring-boot-autoconfigure/pom.xml
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/config/FileControllerConfig.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/config/MetaControllerConfig.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/controller/FileController.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/controller/MetaController.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/datafetcher/SpringSQLMutationDataFetcher.java
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/datafetcher/SpringSQLQueryDataFetcher.java
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/config/FileControllerConfigSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/config/MetaControllerConfigSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/datafetcher/SpringSQLMutationDataFetcherSpec.groovy
  athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/datafetcher/SpringSQLQueryDataFetcherSpec.groovy
Labels: MERGEABLE, NEW FEATURE

#47 Put test to right location
  athena-core/src/test/groovy/com/paiondata/athena/file/identifier/FileIdGeneratorFactorySpec.groovy
Labels: BUG, NEED 1 REVIEW

#48 Fix release error
  .github/workflows/ci-cd.yml
  docs/docs/intro.md
Labels: BUG, CI/CD, NEED 1 REVIEW

#49 修改 athena 项目中的依赖
  athena-spring/athena-spring-boot-autoconfigure/pom.xml
  pom.xml
Labels: BUG, MERGEABLE

#50 File 接口支持 Swagger
  athena-spring/athena-spring-boot-autoconfigure/pom.xml
  athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/config/FileControllerConfig.java
Labels: BREAKING CHANGE, NEED 1 REVIEW
